import { useEffect, useRef, useState } from 'react'
import { ChevronLeft, Star, AlertTriangle, ClipboardCheck } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import {
  fetchMatch, fetchTeamLineup, subscribeMatch,
  fetchMatchByPath, subscribeMatchByPath,
  fetchCompetition, fetchPerson,
  toDate,
} from '../lib/queries'
import { isBulkLineupCompetition, sideIsInherited, resolveSideLineup } from '../lib/lineupResolve'
import { fetchCompetitionTeamSheet } from '../lib/teamSheetQueries'
import { deleteMatch, removeFixtureFromCompetition } from '../lib/adminQueries'
import { configured } from '../firebase'
import ShareButton from '../components/ShareButton'
import VenueLabel from '../components/VenueLabel'
import StatusBadge from '../components/StatusBadge'
import FixtureBanner from '../components/FixtureBanner'
import { MatchTeamIdentity, MatchTeamCrest } from '../components/TeamIdentity'
import PersonAvatar from '../components/PersonAvatar'
import { pomForSide, isLineupEntryPOM, pomColor, pomBgTint } from '../lib/pom'
import { teamAccent } from '../lib/teamAccent'
import { playerUrl, matchUrl } from '../lib/slugify'
import { gameMinuteLabel, periodElapsedMs, formatClock } from '../lib/matchClock'
import { SCORE_LABEL, SCORE_POINTS, scorerLabel, matchTries, cardLabel, cardDurationText, cardCategory } from '../lib/rugbyScoring'
import { useSeoMeta } from '../lib/useSeoMeta'

// Timeline swatch colour by discipline category (red20 shares the red colour).
const CARD_COLOR = { yellow: '#ca8a04', red: '#dc2626' }

// Player attribution is secondary — never surface "Unknown" placeholders.
function cleanName(name) {
  if (!name) return null
  const n = String(name).trim()
  if (!n || n.toLowerCase() === 'unknown' || n.toLowerCase() === 'unknown scorer') return null
  return n
}

// Match slugs are always "team-name-vs-team-name" format generated by buildMatchSlug().
// Build one unified chronological timeline from scores[], cards[] and controlLog[].
// Everything is merged and sorted by matchTimestamp. Reversed events are hidden.
function buildTimeline(match) {
  const events = []
  let maxSort = 0
  const bump = t => { const n = t ?? 0; if (n > maxSort) maxSort = n; return n }

  const teamColor = side =>
    side === 'home' ? (match.homeTeamColor ?? '#334155') : (match.awayTeamColor ?? '#334155')

  // Resolve a scorer/card player's photo from the denormalised lineup entries.
  // Scoring events reference a person by personId; cards reference the lineup entry id.
  const lineup = [...(match.homeLineup ?? []), ...(match.awayLineup ?? [])]
  const photoByPerson = {}
  const photoByEntry  = {}
  for (const e of lineup) {
    if (e.personId) photoByPerson[e.personId] = e.photoUrl ?? null
    if (e.id)       photoByEntry[e.id]         = e.photoUrl ?? null
  }

  for (const e of match.scores ?? []) {
    if (e.status === 'reversed') continue
    const points = e.points ?? SCORE_POINTS[e.scoreType] ?? 0
    events.push({
      key:       `score-${e.id ?? events.length}`,
      type:      'score',
      sort:      bump(e.matchTimestamp),
      // A submitted result's tries carry no timestamp — the scorer is known but
      // the minute is not. Show the event with no minute; never fabricate one.
      time:      e.matchTimestamp != null ? gameMinuteLabel(match, e.matchTimestamp) : null,
      side:      e.side,
      primary:   SCORE_LABEL[e.scoreType] ?? 'Score',
      secondary: `+${points} point${points === 1 ? '' : 's'}`,
      player:    cleanName(e.scorerName),
      playerLabel: scorerLabel(e.scoreType),
      playerPhoto: e.scorerPersonId ? (photoByPerson[e.scorerPersonId] ?? null) : null,
      color:     '#1d4ed8', // scores are always blue regardless of team
    })
  }

  for (const c of match.cards ?? []) {
    if (c.status === 'reversed') continue
    events.push({
      key:       `card-${c.id ?? events.length}`,
      type:      'card',
      sort:      bump(c.matchTimestamp != null ? c.matchTimestamp : (c.minute ?? 0)),
      time:      c.matchTimestamp != null ? gameMinuteLabel(match, c.matchTimestamp) : (c.minute != null ? `${c.minute}'` : null),
      side:      c.side,
      primary:   cardLabel(c.cardType, match),
      secondary: cardDurationText(c, match),
      player:    cleanName(c.playerName),
      playerLabel: 'Player',
      playerPhoto: c.playerPlayerId ? (photoByEntry[c.playerPlayerId] ?? null) : null,
      color:     CARD_COLOR[cardCategory(c.cardType)] ?? '#94a3b8',
    })
  }

  for (const entry of match.controlLog ?? []) {
    let label = null
    if (entry.type === 'match_start' || entry.type === 'period_start') {
      label = entry.period ? `${entry.period} starts` : 'Match starts'
    } else if (entry.type === 'period_end') {
      label = entry.period ? `${entry.period} ends` : 'Period ends'
    } else if (entry.type === 'pause') {
      label = 'Paused'
    } else if (entry.type === 'resume') {
      label = 'Resumed'
    } else if (entry.type === 'abandoned') {
      label = 'Match abandoned'
    }
    if (!label) continue
    events.push({
      key:   `ctrl-${entry.type}-${entry.matchTimestamp ?? 0}-${events.length}`,
      type:  'control',
      sort:  bump(entry.matchTimestamp),
      time:  gameMinuteLabel(match, entry.matchTimestamp),
      side:  null,
      label,
      abandoned: entry.type === 'abandoned',
    })
  }

  // Legacy try attributions from homeScorers/awayScorers when scores[] is absent
  if (!(match.scores?.length) && (match.homeScorers?.length || match.awayScorers?.length)) {
    const addLegacy = (arr, side) => {
      for (const r of arr ?? []) {
        events.push({
          key:       `legacy-${side}-${events.length}`,
          type:      'score',
          sort:      bump(r.minute ?? 0),
          time:      r.minute != null ? `${r.minute}'` : null,
          side,
          primary:   'Try',
          secondary: `+${SCORE_POINTS.try} points`,
          player:    cleanName(r.name),
          playerLabel: 'Scorer',
          color:     '#1d4ed8',
        })
      }
    }
    addLegacy(match.homeScorers, 'home')
    addLegacy(match.awayScorers, 'away')
  }

  const sorted = events.sort((a, b) => a.sort - b.sort)

  // Full time — synthesized at the end for completed matches (no stored entry).
  if (match.status === 'final') {
    sorted.push({
      key:   'ctrl-full-time',
      type:  'control',
      sort:  maxSort + 1,
      time:  null,
      side:  null,
      label: 'Full time',
      emphasis: true,
    })
  }

  return sorted
}

function Spinner() {
  return <div className="flex justify-center py-12"><div className="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"/></div>
}

function fmtMatchDate(val) {
  const d = toDate(val)
  if (!d) return 'TBD'
  return d.toLocaleDateString('en-ZA', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
    + ' · '
    + d.toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit' })
}

// Event content — text block, aligned toward the spine.
function EventContent({ event, align }) {
  return (
    <div className={`min-w-0 ${align === 'right' ? 'text-right' : 'text-left'}`}>
      <div className="text-slate-900 text-sm font-bold leading-tight">{event.primary}</div>
      {event.secondary && (
        <div className="text-[11px] text-slate-500 leading-snug">{event.secondary}</div>
      )}
      {event.player && (
        <div className={`flex items-center gap-1.5 mt-0.5 ${align === 'right' ? 'justify-end' : ''}`}>
          {align === 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">{event.playerLabel}: {event.player}</span>
          )}
          <PersonAvatar name={event.player} photoUrl={event.playerPhoto} size={18} />
          {align !== 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">{event.playerLabel}: {event.player}</span>
          )}
        </div>
      )}
    </div>
  )
}

// Node on the spine: colored circle + timestamp stacked below it, both centered.
// bg-white masks the spine line behind the node so the dot floats cleanly.
function TimeNode({ time, color }) {
  return (
    <div className="relative z-10 flex flex-col items-center gap-1 bg-white px-2 shrink-0">
      <span className="w-3 h-3 rounded-full border-2 border-white shadow-sm shrink-0"
        style={{ backgroundColor: color ?? '#cbd5e1', boxShadow: `0 0 0 1.5px ${color ?? '#cbd5e1'}33` }} />
      {time && (
        <span className="font-mono text-[10px] font-bold text-slate-400 tabular-nums leading-none whitespace-nowrap">
          {time}
        </span>
      )}
    </div>
  )
}

// Phase marker (period start/end, full time) — full-width centered divider.
// Has a horizontal tick that crosses the spine so it reads as a structural marker.
// The abandoned marker is emphasised in red: everything above it is the frozen,
// stopped attempt; anything below (on replay) is the fresh game.
function PhaseMarker({ event }) {
  const ab = event.abandoned
  return (
    <div className="flex items-center gap-0 py-0.5">
      <div className={`flex-1 h-px ${ab ? 'bg-red-200' : 'bg-slate-100'}`} />
      <div className="relative z-10 bg-white flex flex-col items-center px-4 gap-0.5">
        <div className={`w-5 h-[2px] rounded-full mb-1 ${ab ? 'bg-red-400' : 'bg-slate-300'}`} />
        <span className={`text-[9px] font-bold uppercase tracking-widest whitespace-nowrap leading-none ${
          ab ? 'text-red-600' : event.emphasis ? 'text-slate-800' : 'text-slate-500'
        }`}>
          {event.label}
        </span>
        {event.time && (
          <span className="font-mono text-[9px] text-slate-400 tabular-nums mt-0.5 leading-none">{event.time}</span>
        )}
      </div>
      <div className={`flex-1 h-px ${ab ? 'bg-red-200' : 'bg-slate-100'}`} />
    </div>
  )
}

function TimelineEvent({ event }) {
  if (event.type === 'control') return <PhaseMarker event={event} />

  // Side = team: home events always left, away events always right.
  const isAway = event.side === 'away'
  return (
    <div className="grid grid-cols-[1fr_3.5rem_1fr] items-start">
      <div className="flex justify-end pr-2 pt-0.5">
        {!isAway && <EventContent event={event} align="right" />}
      </div>
      <TimeNode time={event.time} color={event.color} />
      <div className="flex justify-start pl-2 pt-0.5">
        {isAway && <EventContent event={event} align="left" />}
      </div>
    </div>
  )
}

export default function MatchDetail() {
  const { date, slug, child, season, competitionSlug, matchSlug } = useParams()
  const navigate = useNavigate()
  const { canScore, isPlatformAdmin, isOrgMember } = useAuth()
  // Type-to-confirm safeguard for match deletion (destructive, irreversible).
  const [deleteOpen,    setDeleteOpen]    = useState(false)
  const [deleteText,    setDeleteText]    = useState('')
  const [deleteBusy,    setDeleteBusy]    = useState(false)
  const [deleteError,   setDeleteError]   = useState('')
  const [match,       setMatch]       = useState(null)
  useSeoMeta({ type: 'match', entity: match })
  const [homePlayers, setHomePlayers] = useState([])
  const [awayPlayers, setAwayPlayers] = useState([])
  const [peopleById,  setPeopleById]  = useState({})   // live person docs for line-up members
  const [inheritedLineups, setInheritedLineups] = useState(null)
  const [loading,     setLoading]     = useState(true)
  const [, setTick]                   = useState(0)
  const lineupsLoaded = useRef(false)

  // Tick the live clock once a second. The clock value itself is derived from
  // getElapsedMs() (wall-clock based), so this only forces a re-render — it
  // never drifts. Frozen while paused or once the match is no longer live.
  useEffect(() => {
    if (match?.status !== 'live' || match?.pausedAt) return
    const t = setInterval(() => setTick(n => n + 1), 1000)
    return () => clearInterval(t)
  }, [match?.status, match?.pausedAt])

  useEffect(() => {
    const onMatch = m => {
      setMatch(m); setLoading(false)
    }
    setLoading(true)

    // Rebuild the stored canonical path from whichever route matched, then
    // resolve by it. Competition matches are competition-scoped and dateless;
    // standalone matches are dated, and `child` is present only for a group child.
    const path = matchSlug
      ? `/competitions/${season}/${competitionSlug}/match/${matchSlug}`
      : child
        ? `/match/${date}/${slug}/${child}`
        : `/match/${date}/${slug}`
    if (!configured) { fetchMatchByPath(path).then(onMatch); return }
    return subscribeMatchByPath(path, onMatch)
  }, [date, slug, child, season, competitionSlug, matchSlug])

  useEffect(() => {
    if (!match || lineupsLoaded.current) return
    lineupsLoaded.current = true
    Promise.all([fetchTeamLineup(match.homeTeamId), fetchTeamLineup(match.awayTeamId)])
      .then(([h, a]) => { setHomePlayers(h); setAwayPlayers(a) })
  }, [match?.homeTeamId, match?.awayTeamId])

  // Resolve the LIVE person record for every line-up member, so the name (and
  // profile slug) always reflect the one people/{id} document — an admin name
  // fix shows here without rewriting the frozen copies on the match/sheet.
  useEffect(() => {
    const ids = [...new Set([
      ...(match?.homeLineup ?? []).map(e => e.personId),
      ...(match?.awayLineup ?? []).map(e => e.personId),
      ...(inheritedLineups?.home ?? []).map(e => e.personId),
      ...(inheritedLineups?.away ?? []).map(e => e.personId),
    ].filter(Boolean))]
    if (!ids.length) return
    Promise.all(ids.map(pid => fetchPerson(pid).catch(() => null))).then(list => {
      const map = {}
      list.forEach(p => { if (p) map[p.id] = p })
      setPeopleById(map)
    })
  }, [match?.id, match?.homeLineup, match?.awayLineup, inheritedLineups])

  // Derived line-ups (tournaments/festivals, brief §4/§9): before the freeze a
  // fixture's sheet EQUALS the competition squad minus exceptions, so the
  // public page resolves it from the membership docs rather than the (empty)
  // stored arrays. Re-resolves whenever the subscribed match doc changes —
  // an absence marked at the field shows here on the next snapshot.
  useEffect(() => {
    if (!match?.competitionId) { setInheritedLineups(null); return }
    const needHome = sideIsInherited(match, 'home')
    const needAway = sideIsInherited(match, 'away')
    if (!needHome && !needAway) { setInheritedLineups(null); return }
    let cancelled = false
    fetchCompetition(match.competitionId).then(async c => {
      if (!c || !isBulkLineupCompetition(c)) return
      const get = (tid) => tid
        ? fetchCompetitionTeamSheet(match.competitionId, tid).catch(() => null)
        : Promise.resolve(null)
      const [h, a] = await Promise.all([get(match.homeTeamId), get(match.awayTeamId)])
      if (cancelled) return
      setInheritedLineups({
        home: needHome ? resolveSideLineup(match, 'home', h?.member) : [],
        away: needAway ? resolveSideLineup(match, 'away', a?.member) : [],
      })
    }).catch(() => {})
    return () => { cancelled = true }
  }, [match])

  // Advertise the canonical (clean) URL so search engines and link unfurlers
  // prefer it over any legacy id-based URL the visitor may have arrived through.
  useEffect(() => {
    if (!match) return
    const href = window.location.origin + matchUrl(match)
    let link = document.querySelector('link[rel="canonical"]')
    if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link) }
    link.setAttribute('href', href)
  }, [match])

  if (loading) return <Spinner />
  if (!match) return <div className="px-4 py-12 text-center text-slate-500 text-sm">Match not found.</div>

  const isLive   = match.status === 'live'
  const isPaused = match.status === 'paused'
  const isFinal  = match.status === 'final'
  // §3/§8 presentation flags (driven by data, not new statuses):
  // an untracked live match has no scorer present; a submitted final result
  // has no live timeline and is tagged so the absence is understood.
  const untrackedLive = (isLive || isPaused) && match.tracked !== true
  const submittedResult = isFinal && match.resultSource === 'submitted'
  const hasScore = isLive || isPaused || isFinal
  const homeWon  = isFinal && match.homeScore > match.awayScore
  const awayWon  = isFinal && match.awayScore > match.homeScore

  // Fixture lineups show ONLY the players actually selected for THIS match —
  // the match document's own homeLineup / awayLineup. The team squad
  // (homePlayers / awayPlayers, fetched by teamId) is used purely as a lookup
  // to enrich each entry with a profile slug and captaincy; it is never the
  // display source, so a squad member is not painted onto fixtures they were
  // not picked for. No lineup picked → the section stays empty.
  const buildSelection = (entries, roster) => {
    const byId = new Map((roster ?? []).filter(r => r.personId).map(r => [r.personId, r]))
    return (entries ?? [])
      .map(e => {
        const r = e.personId ? byId.get(e.personId) : null
        const live = e.personId ? peopleById[e.personId] : null   // one people/{id} record
        return {
          id:          e.id,
          personId:    e.personId ?? null,
          personName:  live?.fullName || e.personName || r?.personName || 'Unknown',
          photoUrl:    live?.photoUrl ?? e.photoUrl ?? r?.photoUrl ?? null,
          shirtNumber: e.shirtNumber ?? r?.shirtNumber ?? null,
          // Captaincy and position read from the LINE-UP ENTRY, where the team
          // sheet writes them; the roster join is a legacy fallback only. A
          // pasted captain would not appear if this joined against the roster.
          position:    e.position ?? null,
          personSlug:  live?.slug ?? e.personSlug ?? r?.personSlug ?? null,
          isCaptain:   (e.isCaptain ?? r?.isCaptain) === true,
          isStarter:   !!e.isStarter,
        }
      })
      // Rendered line-ups sort by shirt number — the same order as the review
      // grid (bench is 16+, so starters lead naturally).
      .sort((a, b) => ((a.shirtNumber ?? 999) - (b.shirtNumber ?? 999)) || (Number(b.isStarter) - Number(a.isStarter)))
  }
  const homeEntries = match.homeLineup?.length ? match.homeLineup : (inheritedLineups?.home ?? [])
  const awayEntries = match.awayLineup?.length ? match.awayLineup : (inheritedLineups?.away ?? [])
  const homeSelection = buildSelection(homeEntries, homePlayers)
  const awaySelection = buildSelection(awayEntries, awayPlayers)

  // Running scoreboard clock — counts UP within the current half, exactly as
  // the scorer sees it (it keeps climbing into added time). Hidden during the
  // half-time break, when there is no half clock to show.
  const liveClock = (isLive || isPaused) && match.startedAt && match.currentPeriod !== 'break'
    ? formatClock(periodElapsedMs(match)) : null

  const homeDisplayName = match.homeOrgName ? `${match.homeOrgName} ${match.homeTeamName}` : (match.homeTeamName ?? '')
  const awayDisplayName = match.awayOrgName ? `${match.awayOrgName} ${match.awayTeamName}` : (match.awayTeamName ?? '')
  const shareData = {
    title: hasScore
      ? `${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : `${homeDisplayName} vs ${awayDisplayName}`,
    text: isLive ? `LIVE · ${match.currentPeriod ?? ''} · ${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : isFinal ? `Full time · ${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : `${homeDisplayName} vs ${awayDisplayName}`,
    url: window.location.origin + matchUrl(match),
  }

  const timeline      = buildTimeline(match)
  const hasTimeline   = timeline.length > 0
  const competitionId = match.competitionId
  // Prefer the clean competition-scoped matches URL when the match carries its
  // competition slug + season; fall back to the legacy id-based route.
  const competitionMatchesUrl = (match.competitionSlug && match.competitionSeason)
    ? `/competitions/${match.competitionSeason}/${match.competitionSlug}/matches`
    : competitionId ? `/competitions/${competitionId}/matches` : null

  // Deleting a match is destructive and irreversible, so it sits behind a
  // type-to-confirm dialog (not a one-click browser confirm). Available to the
  // platform admin and to anyone with match authority over either side; the
  // Firestore rules enforce the same on the server.
  const canDeleteMatch = isPlatformAdmin
    || isOrgMember(match.homeOrgId || '')
    || isOrgMember(match.awayOrgId || '')
  const deleteConfirmed = deleteText.trim().toUpperCase() === 'DELETE'

  function openDeleteDialog() {
    setDeleteText('')
    setDeleteError('')
    setDeleteOpen(true)
  }

  // Performs the delete: removes the match doc, clears its competition
  // fixture-membership (if any), and returns to the match's parent.
  async function confirmDeleteMatch() {
    if (!deleteConfirmed || deleteBusy) return
    setDeleteBusy(true)
    setDeleteError('')
    try {
      await deleteMatch(match.id)
      if (competitionId) await removeFixtureFromCompetition(competitionId, match.id).catch(() => {})
      navigate(competitionMatchesUrl || '/admin/matches')
    } catch (e) {
      setDeleteError(e.message || 'Delete failed.')
      setDeleteBusy(false)
    }
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 pb-12 space-y-4">

      {/* Type-to-confirm delete dialog — deliberate friction before a
          destructive, irreversible action. */}
      {deleteOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"
          onClick={() => !deleteBusy && setDeleteOpen(false)}>
          <div className="bg-white rounded-2xl border border-slate-200 shadow-xl w-full max-w-md p-6 space-y-4"
            onClick={(e) => e.stopPropagation()}>
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 rounded-full bg-red-50 flex items-center justify-center shrink-0">
                <AlertTriangle className="w-5 h-5 text-red-600" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-base">Delete this match?</h3>
                <p className="text-sm text-slate-500 mt-1">
                  {match.homeTeamName || 'Home'} vs {match.awayTeamName || 'Away'} will be permanently
                  removed, along with its score and timeline. This cannot be undone.
                </p>
              </div>
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                Type <span className="text-red-600">DELETE</span> to confirm
              </label>
              <input
                autoFocus
                type="text"
                value={deleteText}
                onChange={(e) => setDeleteText(e.target.value)}
                disabled={deleteBusy}
                placeholder="DELETE"
                className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-500/40 focus:border-red-400 disabled:bg-slate-50"
              />
            </div>
            {deleteError && (
              <p className="text-sm text-red-600">{deleteError}</p>
            )}
            <div className="flex items-center justify-end gap-2 pt-1">
              <button
                onClick={() => setDeleteOpen(false)}
                disabled={deleteBusy}
                className="text-sm font-bold text-slate-500 hover:text-slate-900 px-3 py-2 rounded-lg transition-colors disabled:opacity-50">
                Cancel
              </button>
              <button
                onClick={confirmDeleteMatch}
                disabled={!deleteConfirmed || deleteBusy}
                className="text-sm font-bold text-white bg-red-600 hover:bg-red-500 px-4 py-2 rounded-lg transition-colors disabled:opacity-40 disabled:cursor-not-allowed">
                {deleteBusy ? 'Deleting…' : 'Delete match'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Back nav */}
      <div className="flex items-center gap-3">
        <button onClick={() => navigate(-1)}
          className="flex items-center gap-2 min-h-[44px] text-slate-400 hover:text-slate-900 transition-colors text-sm font-medium">
          <ChevronLeft className="w-4 h-4" />
          Back
        </button>
        <div className="ml-auto flex items-center gap-3">
          {canScore && !isFinal && (
            <Link to={`/score/${match.id}`}
              className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              {isLive || isPaused ? '● Score' : 'Score'}
            </Link>
          )}
          {isPlatformAdmin && (
            <Link to={`/score/${match.id}`}
              className="flex items-center gap-1.5 border border-slate-300 hover:border-slate-400 text-slate-600 hover:text-slate-900 font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              Edit
            </Link>
          )}
          {/* Match deletion is destructive — gated to delete-authority and
              guarded by the type-to-confirm dialog below. */}
          {canDeleteMatch && (
            <button onClick={openDeleteDialog}
              className="flex items-center gap-1.5 border border-red-200 hover:border-red-300 text-red-600 hover:text-red-700 font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              Delete
            </button>
          )}
          {competitionMatchesUrl && (
            <Link to={competitionMatchesUrl}
              className="text-[11px] font-bold uppercase tracking-widest text-emerald-600 hover:text-emerald-500 transition-colors truncate">
              Matches →
            </Link>
          )}
        </div>
      </div>

      {/* Result card */}
      <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm">

        {/* Team colour identity band — home colour left, away colour right.
            This is a visual team identifier, not a progress/possession indicator. */}
        <div className="flex h-1.5 rounded-t-2xl overflow-hidden">
          <div className="flex-1" style={{ backgroundColor: match.homeTeamColor ?? '#94a3b8' }} />
          <div className="flex-1" style={{ backgroundColor: match.awayTeamColor ?? '#94a3b8' }} />
        </div>

        {/* Status pill */}
        <div className="flex items-center justify-center gap-2 pt-5 pb-0 px-5">
          <StatusBadge status={match.status} />
          {(match.status === 'live' || match.status === 'paused') && match.currentPeriod && (
            <span className="font-mono text-[9px] text-slate-500 uppercase tracking-widest">{match.currentPeriod}</span>
          )}
        </div>

        {/* Outcome banner (walkover / abandoned / not played) — above the score */}
        <div className="px-5 pt-3"><FixtureBanner match={match} /></div>

        {/* Scoreline — crest centered above name on both sides, mirrored */}
        <div className="flex items-start justify-between gap-3 px-5 py-[30px]">

          {/* Home */}
          <div className="flex-1 flex flex-col items-center gap-2 min-w-0">
            <MatchTeamCrest match={match} side="home" size={40} />
            {/* Fixed two-line min-height so both names top-align regardless of wrapping */}
            <div className="min-h-[2.75rem] flex items-start justify-center w-full">
              <MatchTeamIdentity match={match} side="home" align="center" hideIdentifier
                nameClass="font-display font-bold text-sm leading-tight text-center text-slate-900" />
            </div>
          </div>

          {/* Score */}
          <div className="shrink-0 flex flex-col items-center gap-2">
            {hasScore ? (
              <>
                <div className="flex items-center leading-none">
                  <span className="font-mono font-black tabular-nums leading-none text-slate-900"
                    style={{ fontSize: 64 }}>
                    {match.homeScore}
                  </span>
                  <span className="font-mono font-normal text-slate-300 mx-2 leading-none" style={{ fontSize: 40 }}>–</span>
                  <span className="font-mono font-black tabular-nums leading-none text-slate-900"
                    style={{ fontSize: 64 }}>
                    {match.awayScore}
                  </span>
                </div>
                {isFinal && match.kickCompHome != null && match.kickCompAway != null && (
                  <div className="font-mono text-xs text-slate-400 -mt-1">
                    ({match.kickCompHome}–{match.kickCompAway} kicks)
                  </div>
                )}
                {(() => {
                  const ht = matchTries(match, 'home'), at = matchTries(match, 'away')
                  if (ht == null || at == null || (!isFinal && !isLive && !isPaused)) return null
                  return (
                    <div className="font-mono text-xs text-slate-400 -mt-1">
                      Tries {ht}–{at}
                    </div>
                  )
                })()}
              </>
            ) : (
              <div className="font-mono font-black text-3xl text-slate-400 leading-none">vs</div>
            )}
            {liveClock && (
              <div className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full border ${
                isPaused ? 'bg-amber-50 border-amber-200' : 'bg-red-50 border-red-200'
              }`}>
                <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${isPaused ? 'bg-amber-500' : 'bg-red-500 animate-pulse'}`} />
                <span className={`font-mono text-xs font-bold tabular-nums leading-none ${isPaused ? 'text-amber-600' : 'text-red-600'}`}>
                  {liveClock}
                </span>
              </div>
            )}
          </div>

          {/* Away */}
          <div className="flex-1 flex flex-col items-center gap-2 min-w-0">
            <MatchTeamCrest match={match} side="away" size={40} />
            <div className="min-h-[2.75rem] flex items-start justify-center w-full">
              <MatchTeamIdentity match={match} side="away" align="center" hideIdentifier
                nameClass="font-display font-bold text-sm leading-tight text-center text-slate-900" />
            </div>
          </div>
        </div>

        {/* Meta — date, venue, share */}
        <div className="border-t border-slate-200 px-5 py-5 flex flex-col items-center gap-2 text-center">
          <div className="text-[15px] text-slate-600 leading-snug">{fmtMatchDate(match.scheduledAt)}</div>
          <VenueLabel pitch={match.pitch} venueId={match.venueId} venueSlug={match.venueSlug}
            className="block text-[15px] text-slate-400 leading-snug" />
          {typeof match.sevens === 'boolean' && (
            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full border border-slate-200 bg-slate-50 text-[10px] font-bold uppercase tracking-widest text-slate-500">
              {match.sevens ? 'Sevens' : 'Fifteens'}
            </span>
          )}
          <ShareButton shareData={shareData}
            className="mt-1 min-h-[44px] px-6 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 active:bg-slate-100 text-slate-500 hover:text-slate-900 transition-colors shadow-sm" />
        </div>
      </div>

      {/* Live disclaimer — no scorer has started tracking this match (§3). */}
      {untrackedLive && (
        <div className="flex items-start gap-2 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
          <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
          <p className="text-xs text-amber-700 leading-relaxed">
            This match may not be being live scored. The scoreline could be out of date until a
            result is confirmed.
          </p>
        </div>
      )}

      {/* Submitted-result tag — a bare result with no minute-by-minute (§8). */}
      {submittedResult && (
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
          <ClipboardCheck className="w-4 h-4 text-slate-400 shrink-0" />
          <p className="text-xs text-slate-500 leading-relaxed">
            Result submitted by an administrator — this match was not live scored, so there is no
            minute-by-minute timeline.
          </p>
        </div>
      )}

      {/* Unified timeline */}
      {hasTimeline && (
        <div className="bg-white rounded-2xl border border-slate-200 px-4 py-5 shadow-sm">
          <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-5 text-center">Timeline</div>
          <div className="relative">
            {/* Vertical spine — runs full height, nodes mask it with bg-white */}
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-slate-200 -translate-x-1/2 pointer-events-none" />
            {/* Fixed 28px gap between every event keeps rhythm locked */}
            <div className="relative flex flex-col gap-7">
              {timeline.map(event => (
                <TimelineEvent key={event.key} event={event} />
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Player of the Match — reads either legacy single (playerOfMatch) or
          per-team (playersOfMatch) via pomForSide. When both sides awarded,
          two columns; when one, an inline row. Header colour follows the first
          available award so a competition's chosen POM colour is visible. */}
      {match.status === 'final' && (() => {
        const homePom = pomForSide(match, 'home')
        const awayPom = pomForSide(match, 'away')
        if (!homePom && !awayPom) return null
        const anchor = homePom ?? awayPom
        // Colour resolution (line-up display brief §4): competition-configured
        // POM colour wins; else the awarded player's TEAM colour; else the
        // platform default. The header follows the anchor side.
        const anchorTeamCol = teamAccent(homePom ? match.homeTeamColor : match.awayTeamColor)
        const c      = pomColor(anchor, anchorTeamCol)
        const label  = (homePom && awayPom) ? 'Players of the Match' : 'Player of the Match'
        const items  = [
          homePom ? { pom: homePom, teamName: match.homeTeamName } : null,
          awayPom ? { pom: awayPom, teamName: match.awayTeamName } : null,
        ].filter(Boolean)
        return (
          <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-3">
              <Star className="w-4 h-4" style={{ color: c }} />
              <div className="text-[10px] font-bold uppercase tracking-widest" style={{ color: c }}>{label}</div>
            </div>
            <div className={items.length === 2 ? 'grid grid-cols-2 gap-4' : 'flex items-center gap-3'}>
              {items.map(({ pom, teamName }) => (
                <div key={teamName} className="flex items-center gap-3 min-w-0">
                  <PersonAvatar name={pom.name} photoUrl={pom.photoUrl} size={40} />
                  <div className="min-w-0">
                    <div className="text-slate-900 font-semibold text-sm truncate">{pom.name}</div>
                    <div className="text-[11px] text-slate-500 mt-0.5 truncate">
                      {teamName}{pom.shirtNumber ? ` · #${pom.shirtNumber}` : ''}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )
      })()}

      {/* Lineups */}
      {(homeSelection.length > 0 || awaySelection.length > 0) && (
        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-4">Lineups</div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="flex items-start gap-1.5 mb-3">
                <MatchTeamCrest match={match} side="home" size={20} />
                <MatchTeamIdentity match={match} side="home" hideIdentifier className="flex-1 min-w-0"
                  nameClass="text-[10px] font-bold uppercase tracking-widest text-slate-500 break-words leading-tight" />
              </div>
              <div className="space-y-2">
                {homeSelection.map(p => {
                  const homePom = pomForSide(match, 'home')
                  const isPom = isLineupEntryPOM(homePom, p)
                  const teamCol = teamAccent(match.homeTeamColor)
                  const c = isPom ? pomColor(homePom, teamCol) : null
                  return (
                    // Line-up row order: number slot → captain slot → name (no
                    // avatar). The © slot is reserved on EVERY row so names
                    // stay aligned; the © renders in the TEAM's colour (slate
                    // fallback), 14px bold — the armband reads at a glance.
                    <div key={p.id}
                      className={`flex items-start gap-2 ${isPom ? '-mx-2 px-2 py-1 rounded' : ''}`}
                      style={isPom ? { backgroundColor: pomBgTint(homePom, teamCol) } : undefined}>
                      <span className="font-mono tabular-nums text-[11px] text-slate-400 w-5 text-right shrink-0">{p.shirtNumber ?? '–'}</span>
                      <span className="w-5 shrink-0 text-sm font-bold leading-none text-center"
                        style={{ color: teamCol }}>{p.isCaptain ? '©' : ''}</span>
                      {p.personId
                        ? <Link to={playerUrl({ id: p.personId, slug: p.personSlug })}
                            className={`text-xs break-words leading-tight min-w-0 transition-colors ${isPom ? 'font-semibold' : 'text-slate-700 hover:text-emerald-600'}`}
                            style={isPom ? { color: c } : undefined}>{p.personName}</Link>
                        : <span className={`text-xs break-words leading-tight min-w-0 ${isPom ? 'font-semibold' : 'text-slate-700'}`}
                            style={isPom ? { color: c } : undefined}>{p.personName}</span>}
                      {p.position && <span className="text-[10px] text-slate-400 truncate shrink-0">{p.position}</span>}
                      <span className="flex-1" />
                      {isPom && <span className="text-[9px] font-bold uppercase tracking-widest shrink-0" style={{ color: c }}>POTM</span>}
                    </div>
                  )
                })}
              </div>
            </div>

            <div>
              <div className="flex items-start gap-1.5 mb-3 justify-end">
                <MatchTeamIdentity match={match} side="away" hideIdentifier align="right" className="flex-1 min-w-0"
                  nameClass="text-[10px] font-bold uppercase tracking-widest text-slate-500 break-words leading-tight" />
                <MatchTeamCrest match={match} side="away" size={20} />
              </div>
              <div className="space-y-2">
                {awaySelection.map(p => {
                  const awayPom = pomForSide(match, 'away')
                  const isPom = isLineupEntryPOM(awayPom, p)
                  const teamCol = teamAccent(match.awayTeamColor)
                  const c = isPom ? pomColor(awayPom, teamCol) : null
                  return (
                    // Mirror of the home row: name ← captain slot ← number, so
                    // the two columns read outward from the centre line.
                    <div key={p.id}
                      className={`flex items-start gap-2 justify-end ${isPom ? '-mx-2 px-2 py-1 rounded' : ''}`}
                      style={isPom ? { backgroundColor: pomBgTint(awayPom, teamCol) } : undefined}>
                      {isPom && <span className="text-[9px] font-bold uppercase tracking-widest shrink-0" style={{ color: c }}>POTM</span>}
                      <span className="flex-1" />
                      {p.position && <span className="text-[10px] text-slate-400 truncate shrink-0">{p.position}</span>}
                      {p.personId
                        ? <Link to={playerUrl({ id: p.personId, slug: p.personSlug })}
                            className={`text-xs break-words leading-tight min-w-0 text-right transition-colors ${isPom ? 'font-semibold' : 'text-slate-700 hover:text-emerald-600'}`}
                            style={isPom ? { color: c } : undefined}>{p.personName}</Link>
                        : <span className={`text-xs break-words leading-tight min-w-0 text-right ${isPom ? 'font-semibold' : 'text-slate-700'}`}
                            style={isPom ? { color: c } : undefined}>{p.personName}</span>}
                      <span className="w-5 shrink-0 text-sm font-bold leading-none text-center"
                        style={{ color: teamCol }}>{p.isCaptain ? '©' : ''}</span>
                      <span className="font-mono tabular-nums text-[11px] text-slate-400 w-5 shrink-0">{p.shirtNumber ?? '–'}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
